# Generated by Django 3.1.5 on 2021-02-21 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
