# Generated by Django 3.1.5 on 2021-02-21 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
