# Generated by Django 3.1.5 on 2021-02-21 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20210221_1528'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
