# Generated by Django 3.1.5 on 2021-02-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_delete_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='CS50 Web Project 4 Network', max_length=280),
        ),
    ]
