# Generated by Django 3.1.5 on 2021-02-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_profile_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='imageURL',
            field=models.URLField(blank=True, default='https://media2.s-nbcnews.com/j/streams/2012/August/120826/503231-imagesizer.social_share_1024x768_scale.jpeg', null=True),
        ),
    ]
