# Generated by Django 3.1.5 on 2021-02-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_auto_20210227_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='imageURL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
