# Generated by Django 3.1.5 on 2021-02-27 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_tweet_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='imageURL',
        ),
    ]
